# Generated by Django 5.0.2 on 2024-04-13 17:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account_number', models.CharField(max_length=24)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('birth_date', models.DateField()),
                ('inn', models.CharField(max_length=14)),
                ('status', models.SmallIntegerField(choices=[(0, 'Work'), (1, 'Reject'), (2, 'Close'), (3, 'Not Work')], default=3)),
                ('response_person', models.ManyToManyField(related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
